server.port=8090
spring.application.name=restaurantapi
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb
spring.datasource.username=root
spring.datasource.password=Mohan@8077
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

