#spring.application.name=autowire-demo
# application.properties
#app.example.integer-value=9876
#app.example.decimal-value=1.75
#app.example.boolean-value=true
server.port=8081

spring.thymeleaf.cache=false  # optional but good during development